platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'Mantle', '~> 1.4'
pod 'FLEX', '~> 1.1.0'
pod 'CSNotificationView', '0.4.2'
pod 'FXBlurView', '~> 1.6.2'
pod 'PureLayout'
pod 'SWRevealViewController', '~> 2.3.0'
