platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'Mantle', '~> 1.4'
pod 'ECSlidingViewController', '2.0.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'FLEX', '~> 1.1.0'
pod 'CSNotificationView', '~> 0.4.2'
